#!/usr/bin/env bash

echo "Fixing permissions ..."
  sudo chown -R `whoami` /usr/local

echo "Installing oh-my-zsh"
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh  

echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  brew update

echo "Putting Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing GNU Compiler Collection and dependencies ..."
  brew tap homebrew/dupes
  brew install autoconf automake apple-gcc42

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing freetds"
  brew install freetds

echo "Installing wget ..."
  brew install wget

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.profile
  source ~/.profile

echo "Installing Ruby"
  bash < <(curl -s https://raw.github.com/arunkarthick/laptop/master/ruby)